### ISSUE TITLE
investigate upgrade for mssql jar

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-projection#117]
relates to https://github.com/apache/incubator-pekko-persistence-jdbc/issues/113

**Comment by laglangyue** [comment]
I search the changes in mssql release
https://github.com/microsoft/mssql-jdbc/releases?q=encrypt&expanded=true
look at this picture. 
![image](https://github.com/apache/pekko-projection/assets/35491928/3e693b8c-7de8-4fec-a239-da6a2e700634)

## How to solve this for our test
(1) add `encrypt=true;trustServerCertificate=true"` to jdbc url
(2) or add `encrypt=false` to jdbc url
## What can users do?
users should ensure that the sqlserver enable tls,maybe need some config, so that client can connect to sqlserver with TLS

**Comment by Roiocam** [comment]
Closed with #126
